Repository AMichalMurawski/goit-markup-project-group3, pull requests merged in 2022-10, with the labels that each got.

#19 footer
  src/images/svg.svg
  src/partials/footer.html
  src/sass/components/_footer.scss
Labels: approve

#17 Feature/advantages
  src/images/apple-icecream.png
  src/images/apple-icecream@2x.png
  src/images/heart-icecream.png
  src/images/heart-icecream@2x.png
  src/images/vanilla-icecream.png
  src/images/vanilla-icecream@2x.png
  src/partials/advantages.html
  src/sass/components/_advantages.scss
  src/sass/main.scss
Labels: approve

#16 Create HTML structure
  src/images/fdd.svg
  src/images/person1.jpg
  src/images/person2.jpg
  src/images/person3.jpg
  src/images/slider-icons.svg
  src/index.html
  src/partials/reviews.html
  src/sass/components/_reviews.scss
Labels: approve, comment

#18 create table.html
  src/index.html
  src/partials/table.html
  src/sass/components/_component.scss
Labels: review

#27 Feature/review 4
  src/images/slider-icons.svg
  src/index.html
  src/js/slider.js
  src/partials/reviews.html
  src/sass/components/_reviews.scss
  src/sass/utils/_colors.scss
Labels: review

#24 Feature/about
  src/partials/about.html
  src/sass/components/_about.scss
  src/sass/components/_button.scss
  src/sass/components/_global.scss
  src/sass/main.css
  src/sass/main.css.map
Labels: approve

#26 Update _colors.scss
  src/sass/utils/_colors.scss
Labels: approve

#25 added new html & scss
  src/images/dots.png
  src/images/products-coffee.png
  src/images/products-icecream.png
  src/images/products-milkshake.png
  src/partials/products.html
  src/sass/components/_products.scss
  src/sass/main.css
  src/sass/main.css.map
Labels: to fix, new commit, comment

#40 feature/about
  src/partials/about.html
  src/sass/components/_about.scss
  src/sass/components/_section.scss
  src/sass/main.css
  src/sass/main.css.map
  src/sass/utils/_font.scss
Labels: approve

#55 update
  src/sass/components/_products.scss
  src/sass/main.css
  src/sass/main.css.map
Labels: approve

#60 feature/about
  src/partials/about.html
  src/sass/components/_about.scss
  src/sass/components/_global.scss
  src/sass/components/_section.scss
  src/sass/utils/_transition.scss
Labels: approve
